version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - movies-data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=movies_db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe

  movies_admin:
    build: movies_admin
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./movies_admin/static:/data/static
    command:
      - /bin/sh
      - -c
      - |
       sleep 10
       python manage.py makemigrations
       python manage.py migrate
       uwsgi --strict --ini uwsgi.ini




  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./movies_admin/static:/data/static:ro
    depends_on:
      - movies_admin
    ports:
      - "80:80"
volumes:
  movies-data: